C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapf_fort (f_fortf2pywrap, N)
      external f_fort
      integer N
      real f_fortf2pywrap, f_fort
      f_fortf2pywrap = f_fort(N)
      end

